version: '3.7'

services:
  activemq:
    image: webcenter/activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - activemq_network

networks:
  activemq_network:
    driver: bridge
